spring:
  application:
    name: Asignment_Java5
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ASM_Java5;encrypt=true;trustServerCertificate=true
    username: sa
    password: Strong@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    open-in-view: false
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
server:
  port: 8080
  tomcat:
    max-part-count: 5000
    max-parameter-count: 10000
camera:
  hls-url: http://10.86.42.36:8888/camera/index.m3u8
payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}

